-- Drop old tables
DROP TABLE files;
DROP TABLE word_counts:

-- Create table to store results
CREATE TABLE files(lines STRING);

-- load data into data base using a file on your local system (not HDFS)
LOAD DATA LOCAL INPAT '/swatthot/input.txt' INTO TABLE files;

-- Create a new table using data from the files table
CREATE TABLE word_counts AS
SELECT word,COUNT(word) AS wordCount FROM
(SELECT explode(split(lines,' ')) AS word FROM files) w
GROUP BY word
ORDER BY wordCount DESC;