- name: Create a new user and add to wheel group
  hosts: all
  become: true
  tasks:

    - name: Create a new user
      user:
        name: swatthot_user
        state: present
        create_home: yes

    - name: Add user to wheel group
      user:
        name: swatthot_user
        groups: wheel
        append: yes